name: droid_ui
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.15
  dio: ^5.3.0
  flutter_svg: ^2.0.7
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  permission_handler: ^10.4.3
  fluttertoast: ^8.2.2
  flutter_guid: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  
  min_sdk_android: 21
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios:
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: false
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app_icon.png"
  color_dark: "#2196F3"
  image_dark: "assets/images/app_icon.png"
  android_12:
    image: "assets/images/app_icon.png"
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
  
# flutter pub run flutter_launcher_icons:main -f pubspec.yaml && flutter pub run flutter_native_splash:create 